In [1]:
import os
import pandas as pd
import numpy as np
import operator

In [2]:
dist_2016_path = os.path.join('2016 - DISTRACT.csv')
raw2016 = pd.read_csv(dist_2016_path, header = 0)

dist_2017_path = os.path.join('2017 - DISTRACT.csv')
raw2017 = pd.read_csv(dist_2017_path, header = 0)

dist_2018_path = os.path.join('2018 - DISTRACT.csv')
raw2018 = pd.read_csv(dist_2018_path, header = 0)

viol_2016_path = os.path.join('2016 - VIOLATN.csv')
raw2016_viol = pd.read_csv(viol_2016_path, header = 0)

viol_2017_path = os.path.join('2017 - VIOLATN.csv')
raw2016_viol = pd.read_csv(viol_2017_path, header = 0)

viol_2018_path = os.path.join('2018 - VIOLATN.csv')
raw2016_viol = pd.read_csv(viol_2018_path, header = 0)

In [3]:
raw2016['Year'] = '2016'
raw2017['Year'] = '2017'
raw2018['Year'] = '2018'

In [4]:
raw2018.head(5)

,CASENUM,VEH_NO,REGION,PSU,PJ,PSU_VAR,URBANICITY,STRATUM,MDRDSTRD,PSUSTRAT,WEIGHT,Year
0,201800381338,1,4,56,208,208,1,9,0,20,187.193308,2018
1,201800381338,2,4,56,208,208,1,9,0,20,187.193308,2018
2,201800381338,3,4,56,208,208,1,9,0,20,187.193308,2018
3,201800381338,4,4,56,208,208,1,9,0,20,187.193308,2018
4,201800381366,1,4,56,214,214,1,7,0,20,149.787336,2018

In [5]:
big_raw = raw2016
big_raw = big_raw.append(raw2017)
big_raw = big_raw.append(raw2018)
big_raw = big_raw.reset_index()

C:\Users\youss\Anaconda3v2\lib\site-packages\pandas\core\frame.py:6692: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  sort=sort)

In [6]:
dist_legend = pd.DataFrame([[0,'Not Distracted'],[1,'Looked But Did Not See'],[3,'By Other Occupants'],[4,'By a Moving Object In Vehicle'],[5,'While Talking Or Listening to Cellular Phone'],[6,'While Manipulating Cellular Phone'],[7,'While Adjusting Audio or Climate Controls'],[9,'While Adjusting Audio or Climate Controls'],[10,'While Using Or Recahing For Device'],[12,'Distracted By Outside Person'],[13,'Eating Or Drinking'],[14,'Smoking Related'],[15,'Other Cellular Phone Related'],[16,'No Driver Present'],[17,'Distracted'],[18,'Distracted'],[19,'Distracted'],[92,'Distracted'],[93,'Distracted'],[99,'Not Distracted']])

In [7]:
grouped = big_raw.groupby(['CASENUM']).max()

,index,MDRDSTRD,PJ,PSU,PSUSTRAT,PSU_VAR,REGION,STRATUM,URBANICITY,VEH_NO,WEIGHT,Year
CASENUM,,,,,,,,,,,,
201600014311,1,92,388,44,25,44,4,9,2,2,219.795475,2016
201600014315,3,0,388,44,25,44,4,8,2,2,186.634758,2016
201600014316,4,0,388,44,25,44,4,5,2,1,32.222550,2016
201600014335,6,0,388,44,25,44,4,10,2,2,317.681532,2016
201600014586,7,0,170,24,24,24,4,2,2,1,37.251626,2016
201600014593,9,0,170,24,24,24,4,10,2,2,379.905770,2016
201600014603,13,99,170,24,24,24,4,8,2,4,210.220810,2016
201600014610,15,0,170,24,24,24,4,3,2,2,42.692621,2016
201600014622,17,0,172,24,24,24,4,9,2,2,247.512223,2016
201600014624,18,0,173,24,24,24,4,2,2,1,37.251626,2016
201600015222,20,0,388,44,25,44,4,10,2,2,317.681532,2016
201600015227,23,0,388,44,25,44,4,6,2,3,73.193141,2016
201600015251,24,99,322,10,21,10,4,10,1,1,427.805961,2016
201600015256,26,0,322,10,21,10,4,9,1,2,292.024739,2016
201600015257,27,1,322,10,21,10,4,2,1,1,50.453749,2016
201600015268,28,0,322,10,21,10,4,2,1,1,50.453749,2016
201600015305,29,96,3247,58,6,58,2,10,1,1,248.715418,2016
201600015805,31,0,2907,63,16,63,3,8,2,2,182.433533,2016
201600015883,32,0,2906,63,16,63,3,8,2,1,182.433533,2016
201600015924,34,0,892,27,6,27,2,7,1,2,119.830778,2016
201600015934,36,99,2907,63,16,63,3,9,2,2,183.806638,2016
201600015940,37,0,2907,63,16,63,3,10,2,1,310.404702,2016
201600015944,39,0,892,27,6,27,2,5,1,2,24.569939,2016
201600015948,40,0,388,44,25,44,4,9,2,1,219.795475,2016
201600015958,41,0,388,44,25,44,4,8,2,1,186.634758,2016
201600015960,43,0,2907,63,16,63,3,6,2,2,63.697535,2016
201600015967,44,0,388,44,25,44,4,10,2,1,317.681532,2016
201600016011,46,0,2907,63,16,63,3,9,2,2,183.806638,2016
201600016014,48,98,138,70,16,70,3,10,2,2,215.218122,2016
201600016016,50,0,2907,63,16,63,3,10,2,2,310.404702,2016
...,...,...,...,...,...,...,...,...,...,...,...,...
201801402354,86081,0,257,60,21,60,4,2,1,1,37.526765,2018
201801402362,86083,0,257,60,21,60,4,6,1,2,82.623031,2018
201801402380,86084,0,257,60,21,60,4,2,1,1,37.526765,2018
201801402389,86085,96,257,60,21,60,4,2,1,1,37.526765,2018
201801402390,86087,0,257,60,21,60,4,9,1,2,204.580798,2018
201801402400,86088,0,257,60,21,60,4,2,1,1,37.526765,2018
201801402421,86092,96,257,60,21,60,4,5,1,4,33.219993,2018
201801402428,86094,0,257,60,21,60,4,9,1,2,204.580798,2018
201801402436,86096,0,257,60,21,60,4,8,1,2,194.662175,2018
201801402441,86097,96,257,60,21,60,4,2,1,1,20.556823,2018
201801402453,86099,96,257,60,21,60,4,10,1,2,284.499787,2018
201801402467,86101,96,257,60,21,60,4,6,1,2,82.623031,2018
201801402470,86102,96,257,60,21,60,4,2,1,1,37.526765,2018
201801402483,86103,96,257,60,21,60,4,8,1,1,194.662175,2018
201801402487,86105,3,257,60,21,60,4,9,1,2,204.580798,2018
201801402491,86106,96,257,60,21,60,4,2,1,1,37.526765,2018
201801402496,86107,96,257,60,21,60,4,2,1,1,37.526765,2018
201801402509,86108,96,257,60,21,60,4,10,1,1,284.499787,2018
201801402517,86110,96,257,60,21,60,4,6,1,2,82.623031,2018
201801402527,86113,96,257,60,21,60,4,6,1,3,82.623031,2018
201801402551,86114,96,257,60,21,60,4,3,1,1,34.390993,2018
201801402572,86115,0,257,60,21,60,4,2,1,1,37.526765,2018
201801402576,86117,96,257,60,21,60,4,4,1,2,20.782117,2018
201801402582,86119,96,257,60,21,60,4,6,1,2,82.623031,2018
201801402588,86121,96,257,60,21,60,4,6,1,2,82.623031,2018
201801402590,86123,96,257,60,21,60,4,9,1,2,204.580798,2018
201801402620,86125,96,257,60,21,60,4,8,1,2,194.662175,2018
201801402628,86127,96,257,60,21,60,4,6,1,2,82.623031,2018
201801402629,86129,0,257,60,21,60,4,4,1,2,16.071732,2018
201801402636,86130,96,257,60,21,60,4,10,1,1,284.499787,2018

In [36]:
grouped = grouped.replace({'MDRDSTRD':{0:'Not Distracted',96:'Not Distracted',99:'Not Distracted',17:'Distracted/Unknown Reason',18:'Distracted/Unknown Reason',19:'Distracted/Unknown Reason',92:'Distracted/Unknown Reason',93:'Distracted/Unknown Reason',98:'Distracted/Unknown Reason',1:'Looked But Did Not See',3:'By Other Occupants',4:'By a Moving Object In Vehicle',5:'Cell Phone',6:'Cell Phone',7:'Adjusting Audio or Climate Controls',9:'Adjusting Audio or Climate Controls',10:'Reaching ',12:'Distracted from outside',13:'Eating or Drinking',14:'Smoking Related',15:'Cell Phone',16:'No Driver',97:'Day Dreaming'}})
grouped = grouped.replace({'REGION':{1:'Northeast',2:'Midwest',3:'South',4:'West'}})
grouped = grouped.replace({'URBANICITY':{1:'Urban',2:'Rural'}})

In [38]:
quick_stats = grouped['MDRDSTRD'].value_counts()
quick_stats.to_frame()
quick_path = os.path.join('Results','distracted_stats.csv')
quick_stats.to_csv(quick_path)

C:\Users\youss\Anaconda3v2\lib\site-packages\ipykernel_launcher.py:4: FutureWarning: The signature of `Series.to_csv` was aligned to that of `DataFrame.to_csv`, and argument 'header' will change its default value from False to True: please pass an explicit value to suppress this warning.
  after removing the cwd from sys.path.

In [39]:
region_stats = grouped['REGION'].value_counts()
region_stats.to_frame()
region_path = os.path.join('Results','region_stats.csv')
region_stats.to_csv(region_path)

C:\Users\youss\Anaconda3v2\lib\site-packages\ipykernel_launcher.py:4: FutureWarning: The signature of `Series.to_csv` was aligned to that of `DataFrame.to_csv`, and argument 'header' will change its default value from False to True: please pass an explicit value to suppress this warning.
  after removing the cwd from sys.path.

In [40]:
urb_stats = grouped['URBANICITY'].value_counts()
urb_stats.to_frame()
urb_path = os.path.join('Results','urb_stats.csv')
urb_stats.to_csv(urb_path)

C:\Users\youss\Anaconda3v2\lib\site-packages\ipykernel_launcher.py:4: FutureWarning: The signature of `Series.to_csv` was aligned to that of `DataFrame.to_csv`, and argument 'header' will change its default value from False to True: please pass an explicit value to suppress this warning.
  after removing the cwd from sys.path.